# OpSecurity v1.1 Config File
use-luckperms: true
use-staff-yml: true
login-reminder-interval: 10
enable-login-effects: true
enable-manual-reset: true # Bật/tắt tính năng reset thủ công
max-password-length: 16 # Độ dài tối đa của mật khẩu